DELETE FROM ATTRIBUT;

DELETE FROM PATTE;

DELETE FROM TYPE_CARDINALITE;

DELETE FROM ASSOCIATION;

DELETE FROM ENTITE;

DELETE FROM PARAMETRE;

DELETE FROM CALCULEE_A_PARTIR_DE;

DELETE FROM CALCULEE;

DELETE FROM RUBRIQUE;

DELETE FROM TYPE_DONNEE;

DELETE FROM EDITION_EXERCICE;
	ALTER TABLE EDITION_EXERCICE AUTO_INCREMENT=0;

DELETE FROM COPIE_ELEVE;
	ALTER TABLE COPIE_ELEVE AUTO_INCREMENT=0;

DELETE FROM EXERCICE;
	ALTER TABLE EXERCICE AUTO_INCREMENT=0;

DELETE FROM MEA;
	ALTER TABLE MEA AUTO_INCREMENT=0;

DELETE FROM DD; 
	ALTER TABLE DD AUTO_INCREMENT=0;

DELETE FROM TYPE_EXERCICE;
	ALTER TABLE TYPE_EXERCICE AUTO_INCREMENT=0;

DELETE FROM PROF_GERE_GROUPE;

DELETE FROM ADMINISTRATEUR;

DELETE FROM PROFESSEUR;

DELETE FROM ELEVE;

DELETE FROM UTILISATEUR;
	ALTER TABLE UTILISATEUR AUTO_INCREMENT=0;

DELETE FROM GROUPE;
	ALTER TABLE GROUPE AUTO_INCREMENT=0;

DELETE FROM PROMOTION;
	ALTER TABLE PROMOTION AUTO_INCREMENT=0;








